[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
lazy_static = "1.5.0"
pnet = "0.35.0"
rand = "0.8.5"
ratatui = "0.29.0"
sysinfo = "0.32.1"
tokio = { version="1.41.1", features=["full"]}

[[bin]]
name = "tui"
path = "main.rs"
